/// Flutter icons EstadosIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EstadosIcon
///      fonts:
///       - asset: fonts/EstadosIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EstadosIcon {
  EstadosIcon._();

  static const _kFontFam = 'EstadosIcon';
  static const _kFontPkg = null;

  static const IconData aguascalientes = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baja_california = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baja_california_sur = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campeche = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chiapas = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chihuahua = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ciudad_de_mexico = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colima = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cuahuila = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData durango = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estado_de_mexico = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gerrero = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guanajuato = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hidalgo = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jalisco = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData michoacan = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData morelos = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nayarit = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nuevo_leon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oaxaca = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puebla = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queretaro = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quintana_roo = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData san_luis_potosi = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sinaloa = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sonora = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabasco = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tamaulipas = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tlaxcala = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData veracruz = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yucatan = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zacatecas = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maquina_8 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
